-- Migration number: 0001 	 2026-01-01T00:00:00.000Z
CREATE TABLE IF NOT EXISTS product_keys (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key_value TEXT NOT NULL,
    semver_range TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);